#!/bin/bash

echo "🚨 紧急启用GitHub Pages..."
echo ""
echo "📋 手动步骤（必须完成）："
echo ""
echo "1. 打开浏览器访问："
echo "   https://github.com/sunliangxiaogan/sunliang-blog/settings/pages"
echo ""
echo "2. 在GitHub Pages设置页面："
echo "   ✅ 选择 'Deploy from a branch'"
echo "   ✅ Branch: 'main'"
echo "   ✅ Folder: '/ (root)'"
echo "   ✅ 点击 'Save' 按钮"
echo ""
echo "3. 等待1-2分钟后，GitHub Pages状态将变为："
echo "   ✅ status: 'built'"
echo ""
echo "🌐 最终访问地址："
echo "   主页: https://sunliangxiaogan.github.io/sunliang-blog/"
echo "   联系页面: https://sunliangxiaogan.github.io/sunliang-blog/contact"
echo ""
echo "📊 检查状态: https://github.com/sunliangxiaogan/sunliang-blog/actions"
echo ""
echo "⚠️  这是最关键的一步！请立即访问上面的链接完成设置。"